### PR TITLE
Fixes double handling issue (Issue #51)

### PR DESCRIPTION
**Pull request by enzedonline**
When drag/drop or copy/paste from file system, the image is added twice to the editor - one original, one compressed. This was the behaviour originally reported in #51 

It's replicated in the [code pen here](https://codepen.io/enzedonline/pen/gONrmBX?editors=0011).

Oddly doesn't occur when running in the dev server.

Updated `ImageDrop` so that drop and paste event listeners are registered with `useCapture=true`, `event.stopPropgation` called to stop event bubbling in the following places:
- `handleDrop` if image files found
- `handleDrop` if dataTransfer items found
- `handleDataTransferList` if image files found

Tested and [confirmed](https://github.com/benwinding/quill-image-compress/issues/51#issuecomment-2241472766) on Windows. Probably needs double checking on Mac (and Linux??) - sorry, no access to either myself.

Also:
- updated version in package.json -> 2.0.3
- updated script tag url in readme & fixed exclamation not rendering

### CODE REVIEW

**Comment by bacinet02** [comment]
Hello, 
I can test on Linux. But I have not enough skills to build quill.imageCompressor.min.js :-(

**Comment by enzedonline** [comment]
@bacinet02 no problem, you can download the compiled JS for this PR [here](https://1drv.ms/u/s!AppilyLm3gHit50pA6NFi-Wm4n8RyQ)

**Comment by ThomasTJdev** [comment]
Thanks for this PR @enzedonline . Using it on Win, Linux and Mac.

**Comment by bacinet02** [comment]
Thanks for the PR @enzedonline .
I have tested on Linux with firefox. But it doesn't works...
Before, when I pasted an image, the image was doubled in the editor.
Now, when I past an image, NO image appears in the editor.

Here is the configuration of the module:
```
modules: {
  imageCompressor: {
   quality: 0.75,
   maxWidth: 1200,
   maxHeight: 1200,
   imageType: 'image/jpeg',
   debug: true,
   suppressErrorLogging: false,
   handleOnPaste: true, 
   insertIntoEditor: undefined,
  }, 
  ...
}
```

And here is the log (firefox console):
```
</> quill-image-compress:  drop fired 
drop { target: div.ql-editor, buttons: 0, clientX: 111, clientY: 328, layerX: 110, layerY: 37 }
quill.imageCompressor.min.js:1:14381
</> quill-image-compress:  handleDrop 
Object { evt: drop }
quill.imageCompressor.min.js:1:14689
</> quill-image-compress:  handleDrop found files 
Object { evt: drop, files: FileList(1), imageFiles: (1) […] }
quill.imageCompressor.min.js:1:14874
</> quill-image-compress:      pasteFilesIntoQuill pasting 1 images... quill.imageCompressor.min.js:1:16641
</> quill-image-compress:      pasteFilesIntoQuill pasting image (0) quill.imageCompressor.min.js:1:16914
</> quill-image-compress:  onImageDrop 
Object { dataUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACoCAMAAABt9SM9AAAAk1BMVEUFCjD33x4AAAAAADDw2R9lXSspKC7/6B0yMC//5h354R7eyBtVTQr95B/WwRrArRdeVQvjzRyShBKbjBNlWwzNuRmEdxDo0Ry3pRaWiBJHQAmwnxWNgBE9NwdqYA0iHwR1ag43MgellRQZFwNWTgpKQwkSEAPGsxh7bw8rJwUeGwMkIAQxLQaomBR4bA5qXw0REy9tQCKkAAAD+ElEQVR4nO3df1PiOByA8W3tXbZZQkGggAoqiric7t77f3VHS38kberMd26HvTPP5z9KZMZnSjcNYf3yBQAAAAAAAAAAAAAAAAD+Q64u5nf/pv/e1VedXET0x/+/1tVXpS9CfY5Y0UWkxCIWsQYQS4BYAsQSIJYAsQSIJUAsAWIJEEuAWALEEiCWALEEiCVALAFiCRBLgFgCxBIglgCxBIglQCwBYgkQS4BYAsQSIJYAsQSIJUAsAWIJEEuAWALEEiCWALEEiCVALAFiCRBLQByr/epS/ylj0oIx/efCjDWufXOLnEotV7Pt8340Wa+W/V4BxtLf4tpNaj9hzO0obu3fI0OsNtbIjqWyl7gjS52Ti1j1UXPXTXWSO29FYtUhXj2t4nhivzSxqg7X3lanc8t6pxKre6x33Wqv8sQqmclgrHjZXLaI1T+xjpsn69E2IZYTy6ytONNIR8u8evRysGYPxCqom+bQ6/n/iFCH8yNnXkqs8tB9feQlqk6k9FTr+1gxKe3G0kkzd983L6Ue7jS3Ox/GGrUvpbmR9saKjvWRvzzLNsRyL/BvzaHbdPgniVVWsOakmRo8t4hVMLs2VvwjSQdyEas8NI1t+dgY308Sq9S9N9wffIvwxOoeqzy+M3UYiOVdz5qxBj+wUupbpDmyBj+wBq/n/VrxPOFG2hMr0mrtqRUvrFrEslos3jy1Viwr+2JFxpmc1g5NLWI5Txn9/tir1awrE6uXa/GzE2tbn1rE6j2t1TR3a9X7R4jlG5FGzhz12hBrMFaRa2lNUjeKWB/EKqZd7ST1pbrEE6s93tnZlvQuWqHEsj6osWI921uOss4+QNW+EcchxdIqu21q6XETYd4s0aTTSXzjrslYm5ACinW6Ws+tqaVZNRFeq093TJKfH9q11HOAsYyelWdRPUhtmwg7cx6wqx7fWbXspeZpILG0WlQ3MOvyYxttrAhZeSRr73B+RNVb8XSNa/c/3AcyKdXL9ublYapSpe1ttuVb0132W0+NSlOVvFvHtmkYsdxttW/7R3tH8rM594wdTzfb+cY5kgUyg9dRPKxaqjK3H4wpEutA3oaRyQYjfK8nDiofHFM4hLPqkA6WWDT/9JmHD1rlzat//lh6qMTOnr77d8EXfga1rKyVt9bMuS9UK9+Yclhge0rT/hX8KessOFST+I7N2B4WRKxTidnRSbVLejs/TjdF7qA4nhx0iB+yamMW+ajY3n6/mV8vvF+9PA1Kx6t8UmzGPW4m+WqpOqs2gcQ69yr2bBvjL9UMKkcVX2jtDwsn1i9ALGIRawixBIglwB+wFeDMEvnzQv7+3b/or8AfKAcAAAAAAAAAAAAAAAA+j38ArZxwdcjDpiEAAAAASUVORK5CYII=" }
quill.imageCompressor.min.js:1:9393
</> quill-image-compress:      pasteFilesIntoQuill done quill.imageCompressor.min.js:1:17049
</> quill-image-compress:  downscaling image... 
Object { args: {…}, newHeight: 168, newWidth: 300 }
quill.imageCompressor.min.js:1:3384
</> quill-image-compress:  downscaleImageFromUrl 
Object { dataUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACoCAMAAABt9SM9AAAAk1BMVEUFCjD33x4AAAAAADDw2R9lXSspKC7/6B0yMC//5h354R7eyBtVTQr95B/WwRrArRdeVQvjzRyShBKbjBNlWwzNuRmEdxDo0Ry3pRaWiBJHQAmwnxWNgBE9NwdqYA0iHwR1ag43MgellRQZFwNWTgpKQwkSEAPGsxh7bw8rJwUeGwMkIAQxLQaomBR4bA5qXw0REy9tQCKkAAAD+ElEQVR4nO3df1PiOByA8W3tXbZZQkGggAoqiric7t77f3VHS38kberMd26HvTPP5z9KZMZnSjcNYf3yBQAAAAAAAAAAAAAAAAD+Q64u5nf/pv/e1VedXET0x/+/1tVXpS9CfY5Y0UWkxCIWsQYQS4BYAsQSIJYAsQSIJUAsAWIJEEuAWALEEiCWALEEiCVALAFiCRBLgFgCxBIglgCxBIglQCwBYgkQS4BYAsQSIJYAsQSIJUAsAWIJEEuAWALEEiCWALEEiCVALAFiCRBLQByr/epS/ylj0oIx/efCjDWufXOLnEotV7Pt8340Wa+W/V4BxtLf4tpNaj9hzO0obu3fI0OsNtbIjqWyl7gjS52Ti1j1UXPXTXWSO29FYtUhXj2t4nhivzSxqg7X3lanc8t6pxKre6x33Wqv8sQqmclgrHjZXLaI1T+xjpsn69E2IZYTy6ytONNIR8u8evRysGYPxCqom+bQ6/n/iFCH8yNnXkqs8tB9feQlqk6k9FTr+1gxKe3G0kkzd983L6Ue7jS3Ox/GGrUvpbmR9saKjvWRvzzLNsRyL/BvzaHbdPgniVVWsOakmRo8t4hVMLs2VvwjSQdyEas8NI1t+dgY308Sq9S9N9wffIvwxOoeqzy+M3UYiOVdz5qxBj+wUupbpDmyBj+wBq/n/VrxPOFG2hMr0mrtqRUvrFrEslos3jy1Viwr+2JFxpmc1g5NLWI5Txn9/tir1awrE6uXa/GzE2tbn1rE6j2t1TR3a9X7R4jlG5FGzhz12hBrMFaRa2lNUjeKWB/EKqZd7ST1pbrEE6s93tnZlvQuWqHEsj6osWI921uOss4+QNW+EcchxdIqu21q6XETYd4s0aTTSXzjrslYm5ACinW6Ws+tqaVZNRFeq093TJKfH9q11HOAsYyelWdRPUhtmwg7cx6wqx7fWbXspeZpILG0WlQ3MOvyYxttrAhZeSRr73B+RNVb8XSNa/c/3AcyKdXL9ublYapSpe1ttuVb0132W0+NSlOVvFvHtmkYsdxttW/7R3tH8rM594wdTzfb+cY5kgUyg9dRPKxaqjK3H4wpEutA3oaRyQYjfK8nDiofHFM4hLPqkA6WWDT/9JmHD1rlzat//lh6qMTOnr77d8EXfga1rKyVt9bMuS9UK9+Yclhge0rT/hX8KessOFST+I7N2B4WRKxTidnRSbVLejs/TjdF7qA4nhx0iB+yamMW+ajY3n6/mV8vvF+9PA1Kx6t8UmzGPW4m+WqpOqs2gcQ69yr2bBvjL9UMKkcVX2jtDwsn1i9ALGIRawixBIglwB+wFeDMEvnzQv7+3b/or8AfKAcAAAAAAAAAAAAAAAA+j38ArZxwdcjDpiEAAAAASUVORK5CYII=", dataUrlCompressed: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCACoASwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDwyiiivSMgooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAopNw9RRuX1H50ALRSbl9R+dG5fUfnQAtFJuX1H50bl9R+dAC0Um5fUfnRuX1H50ALRSbl9R+dG5fUfnQAtFJuX1H50bl9R+dAC0Um5fUfnSgg9DQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB9LfDID/AIVxovA/1b/+jHrrcD0H5Vyfwy/5Jxov/XN//Rj11lfkGY/75W/xS/Nnt0vgXoGB6D8qMD0H5UUVxFhgeg/KjA9B+VFFABgeg/KjA9B+VFFABgeg/KjA9B+VFFABgeg/KjA9B+VFFABgeg/Kvnb4vf8AJQrn/r3h/wDQa+ia+dvi9/yUO5/694f/AEGvpuFP9+f+F/mjkxn8P5nC0UUV+jHmBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAfS/wy/wCScaL/ANc3/wDRj11lcn8Mv+ScaL/1zf8A9GPXWV+P5j/vlb/FL82e3S+BegUUUVxlhRRRQAUUUUAFFFFABRRRQAV87fF7/kodz/17w/8AoNfRNfO3xe/5KHc/9e8P/oNfTcKf78/8L/NHJjP4fzOFooor9GPMCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA+l/hl/wAk40X/AK5v/wCjHrrK5P4Zf8k40X/rm/8A6Meusr8fzH/fK3+KX5s9ul8C9AooorjLCiiigAophljBwZEBHbcKcrKwyrAj1BzTsAtFFRzTw28fmTyxxJ/ekYKPzNCVwJKKq22p6fePstb+1nb+7FMrn9DVqhpp2YBXzt8Xv+Sh3P8A17w/+g19E187fF7/AJKHc/8AXvD/AOg19Lwp/vz/AML/ADRyYz+H8zhaKKK/RjzAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAPpf4Zf8k40X/rm/wD6Meusrk/hl/yTjRf+ub/+jHrrK/H8x/3yt/il+bPbpfAvQKKKK4ywo70Ud6APkbxX/wAjjrn/AGEJ/wD0Y1e6/BT/AJJ//wBvkv8AJa8K8V/8jjrn/YQn/wDRjV7r8Ff+Sfj/AK/Jf5LX2+ef8i6P/bv5HBh/4rNP4i+NR4M0NJIFSTUbolLZG6LgcuR3AyOPUivm3U9X1HWrtrrUr2e6mYk7pXJxnsB0A9hxXpHx3aX/AISnTVYnyRYgoO2d7Z/kKofBePTJPGzC/ETXAt2NmJMY8zIzjP8AFtzj8aMsp0sHl/1pRvK1339PLzCq3OpyX0POyJIXBIZHGCOxHoa9a+F3xJ1BNUt9A1iaa8t7hvLt5ny8kTnoCepX69PoK9c8S+GtO8U6RLp+oQq24Hypdvzwt2ZT/Tv0NVPCvgjRfCFvtsLffdMuJLuXBkf2z/CPYfjmuHFZ3hcXhXGrT97ou3nf/gFwoThO6eh0dfO3xe/5KHc/9e8P/oNfRNfO3xe/5KHc/wDXvD/6DUcKf78/8L/NDxn8P5nC0UUV+jHmBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAfS/wy/wCScaL/ANc3/wDRj11lcn8Mv+ScaL/1zf8A9GPXWV+P5j/vlb/FL82e3S+BegUUUVxlhR3oo70AfI3iv/kcdc/7CE//AKMavdfgr/yT8f8AX5L/ACWvCvFf/I465/2EJ/8A0Y1e6/BX/kn4/wCvyX+S19vnn/Iuj6x/I4MP/FZJ8VvBc/irRIbnT036jYlmSMdZUONyj34BH4jvXzmRLbT4IeKaJvdWRgfzBBr7Mrl/E/w+8PeK2M19aGK8Ix9qtzsk/Hs34g15WU50sLD2NZXj0fb/AIBtWoc75o7njXh34xeItGCw35XVbYADbcNiQD2kHP8A30DXtPhTxzoni+DNhOUulXdJaTYEij1x/EPcevOK8Y8V/CDWtBhlvNPkXUrGMFm2LtlRRzkr3A9QT9BXBWF/daZfw31lO8FzAweORDyp/wA9u9etWy3A5jTdTDNKXdfqv6ZhGrUpO0z7Ir52+L3/ACUO5/694f8A0Gvc/DOtL4i8NafqyqFNzEGdV6K44YD6MDXhnxe/5KHc/wDXvD/6DXn8LwlDMZQluotfijXFu9JNHC0UUV+iHmBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAfS/wy/5Jxov/XN//Rj11lcn8Mv+ScaL/wBc3/8ARj11lfj+Y/75W/xS/Nnt0vgXoFUtW1ew0LTZdQ1K4W3tY/vOQTyegAHJPtV2qeq6Xaa1pdxpt/EJbW4TY6n9CPQg4IPYiuanyc659utt7FO9tDyaT45o/ia2SKw8rQw5WZ3G6ZgRjcAOFwecc5x1r0mTxp4YisDfNr2nm3C7srOpY+wUHcT7YzXgXiv4Ya94du5WtrWbUNOzmO4gTcQPR1HKkevT3rjFgmaYwrFIZQcbAp3flX2TybAYuEZ4eVku2t/W+zOH29SDakixq96NS1q/v1UoLm4kmCnqNzE4/Wvoj4PWj23w6tGcEfaJpZQD6bto/wDQa8k8JfC/XfEV5E93azafpoOZJ502Mw9EU8kn1xj+VfSFlZwafYwWVrGI7eCNY40HZQMCufiDGUXSjhqbu09fKxeGhK7mzx3xr8ZbqG5udL0C1a3eJ2ikurlfnDAkEKh6cjqc/QV0fgn4q6TrOnRW2tXkNjqka7XaY7I5sfxBjwCfQ49qb8RPhdH4olOqaS8VvquAJEfhLgD1I6Njv37+teH6p4U1/RpHTUNIvIdnVzEWT8GGVP4GqwuFy3G4ZU4e7Jeet/nuv60FOdWnO71R9M6t428OaJZNdXWr2jALlYoZVkeT2VVJJ+vT1r5SnkWa4llSNY1dywReignoKfbWd1ePstbaadum2JCx/SvRPBvwi1bV7qK61yGTT9OUhmjk4mlH90L1X6nHsDXfhsNhcohKU6mr/TsjOcp1mkkeqfCu2ltfhvpKTLtZ1kkA/wBlpGI/MEH8a8n+L3/JQ7n/AK94f/Qa+hoYo7eGOGFFjijUIiKMBVAwAK+efi9/yUO5/wCveH/0GvN4cq+2zSpU/mUn97Rrily0UjhaKKK/QDzQooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAPpf4Zf8k40X/rm/wD6Meusr4+EjqMCRwPQMRR5sv8Az1k/77NfHYnhR1q06vtrczb+Hu79zujjOWKVj7Bor4+82X/nrJ/32aPNl/56yf8AfZrH/U5/8/v/ACX/AO2H9e/un2DS8+tfHvmy/wDPWT/vs0ebL/z1k/77NH+pz/5/f+S//bB9e/un2DRXx95sv/PWT/vs0ebL/wA9ZP8Avs0f6nP/AJ/f+S//AGwfXv7p9g0vNfHvmy/89ZP++zR5sv8Az1k/77NH+pz/AOf3/kv/ANsH17+6fYXPrSV8febL/wA9ZP8Avs0ebL/z1k/77NH+pz/5/f8Akv8A9sH17+6fYNfO3xe/5KHc/wDXvD/6DXD+bL/z1k/77NISWOWJJ9Sc16eU5B/Z9d1vac2lrWt2832Mq2J9pHlsJRRRX0hyhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB//2Q==" }
quill.imageCompressor.min.js:1:11429
</> quill-image-compress:  insertToEditor 
Object { url: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCACoASwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDwyiiivSMgooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAopNw9RRuX1H50ALRSbl9R+dG5fUfnQAtFJuX1H50bl9R+dAC0Um5fUfnRuX1H50ALRSbl9R+dG5fUfnQAtFJuX1H50bl9R+dAC0Um5fUfnSgg9DQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB9LfDID/AIVxovA/1b/+jHrrcD0H5Vyfwy/5Jxov/XN//Rj11lfkGY/75W/xS/Nnt0vgXoGB6D8qMD0H5UUVxFhgeg/KjA9B+VFFABgeg/KjA9B+VFFABgeg/KjA9B+VFFABgeg/KjA9B+VFFABgeg/Kvnb4vf8AJQrn/r3h/wDQa+ia+dvi9/yUO5/694f/AEGvpuFP9+f+F/mjkxn8P5nC0UUV+jHmBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAfS/wy/wCScaL/ANc3/wDRj11lcn8Mv+ScaL/1zf8A9GPXWV+P5j/vlb/FL82e3S+BegUUUVxlhRRRQAUUUUAFFFFABRRRQAV87fF7/kodz/17w/8AoNfRNfO3xe/5KHc/9e8P/oNfTcKf78/8L/NHJjP4fzOFooor9GPMCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA+l/hl/wAk40X/AK5v/wCjHrrK5P4Zf8k40X/rm/8A6Meusr8fzH/fK3+KX5s9ul8C9AooorjLCiiigAophljBwZEBHbcKcrKwyrAj1BzTsAtFFRzTw28fmTyxxJ/ekYKPzNCVwJKKq22p6fePstb+1nb+7FMrn9DVqhpp2YBXzt8Xv+Sh3P8A17w/+g19E187fF7/AJKHc/8AXvD/AOg19Lwp/vz/AML/ADRyYz+H8zhaKKK/RjzAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAPpf4Zf8k40X/rm/wD6Meusrk/hl/yTjRf+ub/+jHrrK/H8x/3yt/il+bPbpfAvQKKKK4ywo70Ud6APkbxX/wAjjrn/AGEJ/wD0Y1e6/BT/AJJ//wBvkv8AJa8K8V/8jjrn/YQn/wDRjV7r8Ff+Sfj/AK/Jf5LX2+ef8i6P/bv5HBh/4rNP4i+NR4M0NJIFSTUbolLZG6LgcuR3AyOPUivm3U9X1HWrtrrUr2e6mYk7pXJxnsB0A9hxXpHx3aX/AISnTVYnyRYgoO2d7Z/kKofBePTJPGzC/ETXAt2NmJMY8zIzjP8AFtzj8aMsp0sHl/1pRvK1339PLzCq3OpyX0POyJIXBIZHGCOxHoa9a+F3xJ1BNUt9A1iaa8t7hvLt5ny8kTnoCepX69PoK9c8S+GtO8U6RLp+oQq24Hypdvzwt2ZT/Tv0NVPCvgjRfCFvtsLffdMuJLuXBkf2z/CPYfjmuHFZ3hcXhXGrT97ou3nf/gFwoThO6eh0dfO3xe/5KHc/9e8P/oNfRNfO3xe/5KHc/wDXvD/6DUcKf78/8L/NDxn8P5nC0UUV+jHmBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAfS/wy/wCScaL/ANc3/wDRj11lcn8Mv+ScaL/1zf8A9GPXWV+P5j/vlb/FL82e3S+BegUUUVxlhR3oo70AfI3iv/kcdc/7CE//AKMavdfgr/yT8f8AX5L/ACWvCvFf/I465/2EJ/8A0Y1e6/BX/kn4/wCvyX+S19vnn/Iuj6x/I4MP/FZJ8VvBc/irRIbnT036jYlmSMdZUONyj34BH4jvXzmRLbT4IeKaJvdWRgfzBBr7Mrl/E/w+8PeK2M19aGK8Ix9qtzsk/Hs34g15WU50sLD2NZXj0fb/AIBtWoc75o7njXh34xeItGCw35XVbYADbcNiQD2kHP8A30DXtPhTxzoni+DNhOUulXdJaTYEij1x/EPcevOK8Y8V/CDWtBhlvNPkXUrGMFm2LtlRRzkr3A9QT9BXBWF/daZfw31lO8FzAweORDyp/wA9u9etWy3A5jTdTDNKXdfqv6ZhGrUpO0z7Ir52+L3/ACUO5/694f8A0Gvc/DOtL4i8NafqyqFNzEGdV6K44YD6MDXhnxe/5KHc/wDXvD/6DXn8LwlDMZQluotfijXFu9JNHC0UUV+iHmBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAfS/wy/5Jxov/XN//Rj11lcn8Mv+ScaL/wBc3/8ARj11lfj+Y/75W/xS/Nnt0vgXoFUtW1ew0LTZdQ1K4W3tY/vOQTyegAHJPtV2qeq6Xaa1pdxpt/EJbW4TY6n9CPQg4IPYiuanyc659utt7FO9tDyaT45o/ia2SKw8rQw5WZ3G6ZgRjcAOFwecc5x1r0mTxp4YisDfNr2nm3C7srOpY+wUHcT7YzXgXiv4Ya94du5WtrWbUNOzmO4gTcQPR1HKkevT3rjFgmaYwrFIZQcbAp3flX2TybAYuEZ4eVku2t/W+zOH29SDakixq96NS1q/v1UoLm4kmCnqNzE4/Wvoj4PWj23w6tGcEfaJpZQD6bto/wDQa8k8JfC/XfEV5E93azafpoOZJ502Mw9EU8kn1xj+VfSFlZwafYwWVrGI7eCNY40HZQMCufiDGUXSjhqbu09fKxeGhK7mzx3xr8ZbqG5udL0C1a3eJ2ikurlfnDAkEKh6cjqc/QV0fgn4q6TrOnRW2tXkNjqka7XaY7I5sfxBjwCfQ49qb8RPhdH4olOqaS8VvquAJEfhLgD1I6Njv37+teH6p4U1/RpHTUNIvIdnVzEWT8GGVP4GqwuFy3G4ZU4e7Jeet/nuv60FOdWnO71R9M6t428OaJZNdXWr2jALlYoZVkeT2VVJJ+vT1r5SnkWa4llSNY1dywReignoKfbWd1ePstbaadum2JCx/SvRPBvwi1bV7qK61yGTT9OUhmjk4mlH90L1X6nHsDXfhsNhcohKU6mr/TsjOcp1mkkeqfCu2ltfhvpKTLtZ1kkA/wBlpGI/MEH8a8n+L3/JQ7n/AK94f/Qa+hoYo7eGOGFFjijUIiKMBVAwAK+efi9/yUO5/wCveH/0GvN4cq+2zSpU/mUn97Rrily0UjhaKKK/QDzQooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAPpf4Zf8k40X/rm/wD6Meusr4+EjqMCRwPQMRR5sv8Az1k/77NfHYnhR1q06vtrczb+Hu79zujjOWKVj7Bor4+82X/nrJ/32aPNl/56yf8AfZrH/U5/8/v/ACX/AO2H9e/un2DS8+tfHvmy/wDPWT/vs0ebL/z1k/77NH+pz/5/f+S//bB9e/un2DRXx95sv/PWT/vs0ebL/wA9ZP8Avs0f6nP/AJ/f+S//AGwfXv7p9g0vNfHvmy/89ZP++zR5sv8Az1k/77NH+pz/AOf3/kv/ANsH17+6fYXPrSV8febL/wA9ZP8Avs0ebL/z1k/77NH+pz/5/f8Akv8A9sH17+6fYNfO3xe/5KHc/wDXvD/6DXD+bL/z1k/77NISWOWJJ9Sc16eU5B/Z9d1vac2lrWt2832Mq2J9pHlsJRRRX0hyhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB//2Q==" }
quill.imageCompressor.min.js:1:11641

```

Thanks for help

**Comment by enzedonline** [comment]
@bacinet02 hi, sorry, just saw this

Did it definitely work on previous versions with Firefox? It's never worked on Windows/Firefox. I didn't attempt to address that with this PR.

**Comment by enzedonline** [comment]
Odd ... now I've just re-tested on Firefox, it works exactly as it should for me (Windows).

I fired up a virtual Ubuntu and it seems to work for me there as well:

1. copy file from Ubuntu Files app, paste into Quill
2. drag from Ubuntu Files app, drop into Quill
3. insert image with Quill image button
4. copy/paste image with text as HTML
5. copy image file from browser, paste into Quill

https://github.com/user-attachments/assets/d401925a-de8b-42cf-be8e-11b550de323b

**Comment by bacinet02** [comment]
Hello,

due to hollydays, I will test in few days only...
But thanks for the work 
:-)

**Comment by benwinding** [comment]
Tested and LGTM 👌 apologies for the delay 🙏 
Thanks @enzedonline for contributing and making a codepen link replicating the issue!
Will merge in and deploy

**Pull request merged**
